### ISSUE TITLE
Migrate existing site to 2021.pwasummit.org

### ISSUE THREAD

**Issue by aarongustafson** [PWA-Summit/pwasummit.org#29]
* [x] Check DNS
* [x] Push to 2021 branch
* [x] Set up Netlify to respond

**Comment by webmaxru** [comment]
Yes, I'm on it. I created a clone of the repo and setting up 2021.pwasummit.org website on Netlify for it.
So we can continue using the main repo & Netlify project for "this year's edition" website

**Comment by webmaxru** [comment]
https://2021.pwasummit.org/ - online

As mentioned above - let's have 2021's snapshot in a separate repo, not branch. I cloned to "2021.pwasummit.org" repo. This way we can safely manipulate all branches in the "current" (main) repo "pwasummit.org"

**Comment by aarongustafson** [comment]
Ok. Sam and I were going to use branch deploys in Netlify, but that's fine.
